version: "3.3"

services:
  server:
    image: lucasrahn09/digimarkets_server:latest
    volumes:
      - ./services/server/src:/usr/src/app/src
      - ./services/server/migrations:/usr/src/app/migrations
      - ./logs/server_logs:/var/log/server_logs
    env_file:
      - .env.prod
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs/db_logs:/var/log/postgresql
    env_file:
      - .env.prod
  nextjs:
    image: lucasrahn09/digimarkets_client:latest
    entrypoint: pm2-runtime 'npm start' --error /var/log/nextjs_logs/nextjs_error.log --output /var/log/nextjs_logs/nextjs_output.log
    volumes:
      - ./logs/nextjs_logs:/var/log/nextjs_logs
  nginx:
    image: lucasrahn09/digimarkets_nginx:latest
    volumes:
      - ./logs/nginx_logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - nextjs

volumes:
  postgres_data:
