version: "3.3"

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - ./services/server/src:/usr/src/app/src
      - ./services/server/migrations:/usr/src/app/migrations
      - ./logs/server_logs:/var/log/server_logs
    env_file:
      - .env.dev
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
    ports:
      - "5000:5000"
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs/db_logs:/var/log/postgresql
    env_file:
      - .env.dev

volumes:
  postgres_data:
