version: "3.3"

services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    volumes:
      - ./services/server/src:/usr/src/app/src
      - ./services/server/migrations:/usr/src/app/migrations
      - ./logs/server_logs:/var/log/server_logs
    env_file:
      - .env.dev
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs/db_logs:/var/log/postgresql
    env_file:
      - .env.dev
  nextjs:
    build:
      context: ./services/client
      dockerfile: Dockerfile
      args:
        staging: 1
    entrypoint: pm2-runtime 'npm start' --error ./logs/nextjs_error.log --output ./logs/nextjs_output.log
    volumes:
      - ./logs/nextjs_logs:/usr/src/app/logs
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./data/nginx_logs:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - server
      - nextjs

volumes:
  postgres_data:
