FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY prod.conf /etc/nginx/conf.d/nginx.conf
COPY certs/lujr_ca.key/ /etc/ssl/private/lujr_ca.key
COPY certs/lujr_ca.crt/ /etc/ssl/certs/lujr_ca.crt

EXPOSE 443
EXPOSE 80