"""empty message

Revision ID: 1aa74375071c
Revises: 34285d3bcf86
Create Date: 2022-03-29 19:00:31.721129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa74375071c'
down_revision = '34285d3bcf86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_network', sa.Column('short_name', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'blockchain_network', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockchain_network', type_='unique')
    op.drop_column('blockchain_network', 'short_name')
    # ### end Alembic commands ###
