"""empty message

Revision ID: 2becd6e328b9
Revises: 4b29e9e4239f
Create Date: 2022-03-28 20:05:48.838824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2becd6e328b9'
down_revision = '4b29e9e4239f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'collection', 'blockchain_network', ['network_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    # ### end Alembic commands ###
