"""empty message

Revision ID: 4b29e9e4239f
Revises: 7dc8b511a497
Create Date: 2022-03-28 20:03:36.101495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b29e9e4239f'
down_revision = '7dc8b511a497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blockchain_network', 'chain_id',
               existing_type=sa.VARCHAR(length=34),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('blockchain_network', 'network_id',
               existing_type=sa.VARCHAR(length=34),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blockchain_network', 'network_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=34),
               existing_nullable=False)
    op.alter_column('blockchain_network', 'chain_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=34),
               existing_nullable=False)
    # ### end Alembic commands ###
