"""empty message

Revision ID: b4ab069310aa
Revises: 6822ad6d2fbf
Create Date: 2022-03-28 18:42:27.811723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ab069310aa'
down_revision = '6822ad6d2fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('poo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'poo')
    # ### end Alembic commands ###
