"""empty message

Revision ID: d5dca41d4e7b
Revises: fa6efadd5f06
Create Date: 2022-04-01 21:13:57.237198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5dca41d4e7b'
down_revision = 'fa6efadd5f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('contract_type', sa.String(length=50), nullable=False))
    op.alter_column('collection', 'name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'name',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('collection', 'contract_type')
    # ### end Alembic commands ###
