"""empty message

Revision ID: fa6efadd5f06
Revises: fd3057920f8c
Create Date: 2022-04-01 17:18:33.158760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6efadd5f06'
down_revision = 'fd3057920f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_network', sa.Column('supported', sa.Boolean(), nullable=True))
    op.add_column('collection', sa.Column('search_count', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'search_count')
    op.drop_column('blockchain_network', 'supported')
    # ### end Alembic commands ###
