"""empty message

Revision ID: 18ddd883136a
Revises: 1388f3a3adcc
Create Date: 2022-04-13 19:14:28.741342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ddd883136a'
down_revision = '1388f3a3adcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'name',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=3000),
               existing_nullable=True)
    op.alter_column('collection', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'symbol',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('collection', 'name',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
